### ISSUE TITLE
support https (and wss:// schema)

### ISSUE THREAD

**Issue by adler99** [input-output-hk/cardano-rt-view#124]
Hi,

seems like the https connection upgrade to websocket connection doesn't work properly.

Error message from my browser's console:
```
Uncaught DOMException: Failed to construct 'WebSocket': The URL 'ws:://some_server:1234/websocket/' is invalid.
    at Object.Haskell.createWebSocket (https:/some_server:1234/haskell.js:82:14)
    at Object.Haskell.initFFI (https://some_server:1234/haskell.js:295:24)
    at https://some_server:1234/:15:13
```

I guess it should be `wss://` for the websocket, if the page was loaded with https.

Serving the page with http works.

Reproduce:

nginx proxy setup with SSL
RTView version 0.2.0

Thanks :-)
Martin

**Comment by dailyinvention** [comment]
I would love to see this implemented.  I would make rtViewer more usable with Apache2 setup.

**Comment by dailyinvention** [comment]
I did a little more investigation, and I think this websocket issue is related to the threepenny-gui library that RTview is using.  I put in a small PR with the owner that should address this issue with the websockets over SSL.

https://github.com/HeinrichApfelmus/threepenny-gui/pull/252

**Comment by dailyinvention** [comment]
This issue should be addressed with these commits on the threepenny-gui side:

https://github.com/HeinrichApfelmus/threepenny-gui/commit/e3cb5cb0ea2c2cfe852642e381ac1d482aa5deeb
https://github.com/HeinrichApfelmus/threepenny-gui/commit/0e2f949d6373892cae1bb2f1378e6909b6fd0b05
